version: "3.9"

services:
  api:
    container_name: docker-dotnet-live-recompilation
    image: mcr.microsoft.com/dotnet/sdk:6.0
    ports:
      - 5001:5001
    volumes:
      - .:/app
    working_dir: /app
    command: dotnet watch run --launch-profile Docker
